package constants

type CFW string

const (
	NextUI CFW = "NextUI"
	MuOS   CFW = "muOS"
	Knulli CFW = "Knulli"
	MinUI  CFW = "MinUI"
)

const MuOSSD1 = "/mnt/mmc"
const MuOSSD2 = "/mnt/sdcard"
const MuOSRomsFolderUnion = "/mnt/union/ROMS"
const NextUIRomsFolder = "/mnt/SDCARD/Roms/"

var NextUIPlatforms = map[string][]string{
	"3do":                                {},
	"3ds":                                {"Nintendo 3DS (3DS)"},
	"acpc":                               {"Amstrad CPC (CPC)"},
	"amiga":                              {"Amiga (PUAE)"},
	"arcade":                             {"Arcade (FBN)"},
	"arduboy":                            {},
	"atari-st":                           {},
	"atari2600":                          {"Atari 2600 (A2600)"},
	"atari5200":                          {"Atari 5200 (A5200)"},
	"atari7800":                          {"Atari 7800 (A7800)"},
	"c128":                               {"Commodore 128 (C128)"},
	"c64":                                {"Commodore 64 (C64)"},
	"cave-story":                         {},
	"cbm-ii":                             {},
	"chailove":                           {},
	"chip-8":                             {},
	"colecovision":                       {"Colecovision (COLECO)"},
	"cpet":                               {"Commodore PET (PET)"},
	"dc":                                 {},
	"dos":                                {},
	"doom":                               {"Doom (PRBOOM)"},
	"fairchild-channel-f":                {},
	"fds":                                {"Famicom Disk System (FDS)"},
	"g-and-w":                            {},
	"galaksija":                          {},
	"gamegear":                           {"Sega Game Gear (GG)"},
	"gb":                                 {"Game Boy (GB)"},
	"gba":                                {"Game Boy Advance (GBA)"},
	"gbc":                                {"Game Boy Color (GBC)"},
	"genesis":                            {"Sega Genesis (MD)"},
	"intellivision":                      {},
	"j2me":                               {},
	"jaguar":                             {},
	"karaoke":                            {},
	"lowres":                             {},
	"lua":                                {},
	"lynx":                               {"Atari Lynx (LYNX)"},
	"media-player":                       {},
	"mega-duck-slash-cougar-boy":         {},
	"msx":                                {"Microsoft MSX (MSX)"},
	"n64":                                {"Nintendo 64 (N64)"},
	"naomi":                              {},
	"nds":                                {"Nintendo DS (NDS)"},
	"neo-geo-cd":                         {},
	"neo-geo-pocket":                     {"Neo Geo Pocket (NGP)"},
	"neo-geo-pocket-color":               {"Neo Geo Pocket Color (NGPC)"},
	"neogeoaes":                          {},
	"neogeomvs":                          {},
	"nes":                                {"Nintendo Entertainment System (FC)"},
	"famicom":                            {"Nintendo Entertainment System (FC)"},
	"odyssey--1":                         {},
	"onscripter":                         {},
	"openbor":                            {},
	"pc-8000":                            {},
	"pc-fx":                              {},
	"pc-9800-series":                     {},
	"philips-cd-i":                       {},
	"pico-8":                             {"Pico-8 (P8)"},
	"pokemon-mini":                       {"Pokémon mini (PKM)"},
	"ports":                              {},
	"psp":                                {"Sony PlayStation Portable (PSP)"},
	"psx":                                {"Sony PlayStation (PS)"},
	"ps2":                                {"Sony PlayStation 2 (PS2)"},
	"quake":                              {},
	"rpg-maker":                          {},
	"saturn":                             {},
	"scummvm":                            {},
	"sega-master-system":                 {"Sega Master System (SMS)"},
	"sega-pico":                          {},
	"sega32":                             {"Sega 32X (32X)"},
	"segacd":                             {"Sega CD (SEGACD)"},
	"sg1000":                             {"Sega SG-1000 (SG1000)"},
	"sharp-x68000":                       {},
	"sinclair-zx81":                      {},
	"snes":                               {"Super Nintendo Entertainment System (SFC)"},
	"sfam":                               {"Super Nintendo Entertainment System (SFC)"},
	"supergrafx":                         {},
	"tg16":                               {"TurboGrafx-16 (PCE)"},
	"ti-83":                              {},
	"tic-80":                             {},
	"turbografx-cd":                      {},
	"uzebox":                             {},
	"vectrex":                            {},
	"vemulator":                          {},
	"vic-20":                             {"Commodore VIC20 (VIC)"},
	"virtualboy":                         {"Virtual Boy (VB)"},
	"vircon-32":                          {},
	"wasm-4":                             {},
	"watara-slash-quickshot-supervision": {},
	"wolfenstein-3d":                     {},
	"wonderswan":                         {"WS"},
	"wonderswan-color":                   {"WSC"},
	"x1":                                 {},
	"zxs":                                {},
}

// ... existing code ...

var MuOSPlatforms = map[string][]string{
	"3do":                                {"3do", "The 3DO Company - 3DO"},
	"acpc":                               {"cpc", "gx4000", "Amstrad"},
	"amiga":                              {"amiga", "Commodore Amiga"},
	"arcade":                             {"arcade", "mame", "cps1", "cps2", "cps3", "fba", "fbneo", "Arcade"},
	"arduboy":                            {"Arduboy"},
	"atari-st":                           {"Atari ST-STE-TT-Falcon"},
	"atari2600":                          {"a2600", "atari", "Atari 2600"},
	"atari5200":                          {"a5200", "Atari 5200"},
	"atari7800":                          {"a7800", "Atari 7800"},
	"c128":                               {"c128", "Commodore C128"},
	"c64":                                {"c64", "Commodore C64"},
	"cave-story":                         {"Cave Story"},
	"cbm-ii":                             {"Commodore CBM-II"},
	"chailove":                           {"ChaiLove"},
	"chip-8":                             {"CHIP-8"},
	"colecovision":                       {"ColecoVision"},
	"cpet":                               {"Commodore PET"},
	"dc":                                 {"dc", "dreamcast", "Sega Dreamcast"},
	"dos":                                {"dos", "DOS"},
	"doom":                               {"doom", "Doom"},
	"fairchild-channel-f":                {"channelf", "Fairchild ChannelF"},
	"fds":                                {"fds", "Nintendo FDS"},
	"g-and-w":                            {"gw", "Handheld Electronic - Game and Watch"},
	"galaksija":                          {"Galaksija Retro Computer"},
	"gamegear":                           {"gg", "Sega Game Gear"},
	"gb":                                 {"gb", "Nintendo Game Boy"},
	"gba":                                {"gba", "Nintendo Game Boy Advance"},
	"gbc":                                {"gbc", "Nintendo Game Boy Color"},
	"genesis":                            {"genesis", "md", "nomad", "Sega Mega Drive - Genesis"},
	"intellivision":                      {"intv", "Mattel - Intellivision"},
	"j2me":                               {"j2me", "java", "Java J2ME"},
	"jaguar":                             {"jaguar", "Atari Jaguar"},
	"lowres":                             {"lowresnx", "Lowres NX"},
	"lua":                                {"Lua Engine"},
	"lynx":                               {"lynx", "Atari Lynx"},
	"media-player":                       {"iptv", "Media Player"},
	"mega-duck-slash-cougar-boy":         {"megaduck", "Mega Duck"},
	"msx":                                {"msx", "msx2", "Microsoft - MSX"},
	"n64":                                {"n64", "Nintendo N64"},
	"naomi":                              {"naomi", "atomiswave", "Sega Atomiswave Naomi"},
	"nds":                                {"ds", "nds", "Nintendo DS"},
	"neo-geo-cd":                         {"neocd", "SNK Neo Geo CD"},
	"neo-geo-pocket":                     {"ngp", "SNK Neo Geo Pocket - Color"},
	"neo-geo-pocket-color":               {"ngpc", "SNK Neo Geo Pocket - Color"},
	"neogeoaes":                          {"neogeo", "SNK Neo Geo"},
	"neogeomvs":                          {"neogeo", "SNK Neo Geo"},
	"nes":                                {"nes", "fc", "Nintendo NES-Famicom"},
	"famicom":                            {"fc", "nes", "Nintendo NES-Famicom"},
	"odyssey--1":                         {"odyssey2", "Magnavox Odyssey - VideoPac"},
	"onscripter":                         {"Onscripter"},
	"openbor":                            {"openbor", "OpenBOR"},
	"pc-8000":                            {"NEC PC-8000 - PC-8800 series"},
	"pc-fx":                              {"NEC PC-FX"},
	"pc-9800-series":                     {"NEC PC98"},
	"philips-cd-i":                       {"cdi", "Philips CDi"},
	"pico-8":                             {"PICO-8"},
	"pokemon-mini":                       {"poke", "pokemini", "Nintendo Pokemon Mini"},
	"ports":                              {"External - Ports"},
	"psp":                                {"psp", "Sony Playstation Portable"},
	"psx":                                {"ps", "ps1", "psx", "Sony Playstation"},
	"quake":                              {"Quake"},
	"rpg-maker":                          {"easyrpg", "RPG Maker 2000 - 2003"},
	"saturn":                             {"saturn", "Sega Saturn"},
	"scummvm":                            {"scummvm", "ScummVM"},
	"sega-master-system":                 {"ms", "sms", "Sega Master System"},
	"sega-pico":                          {"Sega Pico"},
	"sega32":                             {"sega32x", "Sega 32X"},
	"segacd":                             {"segacd", "mdcd", "Sega Mega CD - Sega CD"},
	"sg1000":                             {"sg1000", "Sega SG-1000"},
	"sharp-x68000":                       {"x68000", "x68k", "Sharp X68000"},
	"sinclair-zx81":                      {"zx81", "Sinclair ZX 81"},
	"snes":                               {"snes", "sfc", "Nintendo SNES-SFC"},
	"sfam":                               {"sfc", "snes", "sufami", "Nintendo SNES-SFC"},
	"supergrafx":                         {"supergrafx", "NEC PC Engine SuperGrafx"},
	"tg16":                               {"pce", "tg16", "turbografx", "NEC PC Engine"},
	"ti-83":                              {"Texas Instruments TI-83"},
	"tic-80":                             {"tic80", "TIC-80"},
	"turbografx-cd":                      {"pcecd", "tgcd", "turbografxcd", "NEC PC Engine CD"},
	"uzebox":                             {"Uzebox"},
	"vectrex":                            {"vectrex", "GCE - Vectrex"},
	"vemulator":                          {"VeMUlator"},
	"vic-20":                             {"Commodore VIC-20"},
	"virtualboy":                         {"vb", "Nintendo Virtual Boy"},
	"vircon-32":                          {"Vircon32"},
	"wasm-4":                             {"wasm4", "WASM-4"},
	"watara-slash-quickshot-supervision": {"supervision", "Watara Supervision"},
	"wolfenstein-3d":                     {"Wolfenstein 3D"},
	"wonderswan":                         {"ws", "Bandai WonderSwan-Color"},
	"wonderswan-color":                   {"wsc", "Book Reader"},
	"x1":                                 {"x1", "Sharp X1"},
	"zxs":                                {"spectrum", "Sinclair ZX Spectrum"},
}

var MuOSArtDirectory = map[string]string{
	"3do":                                "The 3DO Company - 3DO",
	"acpc":                               "Amstrad",
	"amiga":                              "Commodore Amiga",
	"arcade":                             "Arcade",
	"arduboy":                            "Arduboy",
	"atari-st":                           "Atari ST-STE-TT-Falcon",
	"atari2600":                          "Atari 2600",
	"atari5200":                          "Atari 5200",
	"atari7800":                          "Atari 7800",
	"c128":                               "Commodore C128",
	"c64":                                "Commodore C64",
	"cave-story":                         "Cave Story",
	"cbm-ii":                             "Commodore CBM-II",
	"chailove":                           "ChaiLove",
	"chip-8":                             "CHIP-8",
	"colecovision":                       "ColecoVision",
	"cpet":                               "Commodore PET",
	"dc":                                 "Sega Dreamcast",
	"doom":                               "Doom",
	"dos":                                "DOS",
	"fairchild-channel-f":                "Fairchild ChannelF",
	"famicom":                            "Nintendo NES-Famicom",
	"fds":                                "Nintendo FDS",
	"g-and-w":                            "Handheld Electronic - Game and Watch",
	"galaksija":                          "Galaksija Retro Computer",
	"gamegear":                           "Sega Game Gear",
	"gb":                                 "Nintendo Game Boy",
	"gba":                                "Nintendo Game Boy Advance",
	"gbc":                                "Nintendo Game Boy Color",
	"genesis":                            "Sega Mega Drive - Genesis",
	"intellivision":                      "Mattel - Intellivision",
	"j2me":                               "Java J2ME",
	"jaguar":                             "Atari Jaguar",
	"karaoke":                            "Karaoke",
	"lowres":                             "Lowres NX",
	"lua":                                "Lua Engine",
	"lynx":                               "Atari Lynx",
	"media-player":                       "Media Player",
	"mega-duck-slash-cougar-boy":         "Mega Duck",
	"msx":                                "Microsoft - MSX",
	"n64":                                "Nintendo N64",
	"naomi":                              "Sega Atomiswave Naomi",
	"nds":                                "Nintendo DS",
	"neo-geo-cd":                         "SNK Neo Geo CD",
	"neo-geo-pocket":                     "SNK Neo Geo Pocket - Color",
	"neo-geo-pocket-color":               "SNK Neo Geo Pocket - Color",
	"neogeoaes":                          "SNK Neo Geo",
	"neogeomvs":                          "SNK Neo Geo",
	"nes":                                "Nintendo NES-Famicom",
	"odyssey--1":                         "Magnavox Odyssey - VideoPac",
	"onscripter":                         "Onscripter",
	"openbor":                            "OpenBOR",
	"pc-8000":                            "NEC PC-8000 - PC-8800 series",
	"pc-9800-series":                     "NEC PC98",
	"pc-fx":                              "NEC PC-FX",
	"philips-cd-i":                       "Philips CDi",
	"pico-8":                             "PICO-8",
	"pokemon-mini":                       "Nintendo Pokemon Mini",
	"ports":                              "External - Ports",
	"psp":                                "Sony Playstation Portable",
	"psx":                                "Sony Playstation",
	"quake":                              "Quake",
	"rpg-maker":                          "RPG Maker 2000 - 2003",
	"saturn":                             "Sega Saturn",
	"scummvm":                            "ScummVM",
	"sega-master-system":                 "Sega Master System",
	"sega-pico":                          "Sega Pico",
	"sega32":                             "Sega 32X",
	"segacd":                             "Sega Mega CD - Sega CD",
	"sfam":                               "Nintendo SNES-SFC",
	"sg1000":                             "Sega SG-1000",
	"sharp-x68000":                       "Sharp X68000",
	"sinclair-zx81":                      "Sinclair ZX 81",
	"snes":                               "Nintendo SNES-SFC",
	"supergrafx":                         "NEC PC Engine SuperGrafx",
	"tg16":                               "NEC PC Engine",
	"ti-83":                              "Texas Instruments TI-83",
	"tic-80":                             "TIC-80",
	"turbografx-cd":                      "NEC PC Engine CD",
	"uzebox":                             "Uzebox",
	"vectrex":                            "GCE - Vectrex",
	"vemulator":                          "VeMUlator",
	"vic-20":                             "Commodore VIC-20",
	"vircon-32":                          "Vircon32",
	"virtualboy":                         "Nintendo Virtual Boy",
	"wasm-4":                             "WASM-4",
	"watara-slash-quickshot-supervision": "Watara Supervision",
	"wolfenstein-3d":                     "Wolfenstein 3D",
	"wonderswan":                         "Bandai WonderSwan-Color",
	"wonderswan-color":                   "Book Reader",
	"x1":                                 "Sharp X1",
	"zxs":                                "Sinclair ZX Spectrum",
}
