package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

const GameDBPSPURL = "https://github.com/niemasd/GameDB-PSP/releases/latest/download/PSP.titles.json"

// outputPath is relative to the working directory set by go generate,
// which is the source directory of the package containing the directive
// (i.e. internal/pspdb/).
const outputPath = "pspdb_generated.go"

func main() {
	fmt.Println("Fetching PSP title database from", GameDBPSPURL)

	resp, err := http.Get(GameDBPSPURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to fetch PSP titles: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "unexpected HTTP status: %s\n", resp.Status)
		os.Exit(1)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read response body: %v\n", err)
		os.Exit(1)
	}

	var titles map[string]string
	if err := json.Unmarshal(data, &titles); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse JSON: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Loaded %d PSP titles\n", len(titles))

	ids := make([]string, 0, len(titles))
	for id := range titles {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen-psp-rom-list; DO NOT EDIT.\n\n")
	sb.WriteString("package pspdb\n\n")
	sb.WriteString("// Titles maps PSP Game IDs to their canonical game titles.\n")
	sb.WriteString("// Source: https://github.com/niemasd/GameDB-PSP\n")
	sb.WriteString("var Titles = map[string]string{\n")
	for _, id := range ids {
		cleanID := strings.NewReplacer("-", "", " ", "").Replace(id)
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", cleanID, titles[id]))
	}
	sb.WriteString("}\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d entries)\n", outputPath, len(titles))
}
