package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

const GameDBPSPURL = "https://github.com/niemasd/GameDB-PSP/releases/latest/download/PSP.titles.json"

// vendoredPath is relative to the project root. The generator is invoked by
// go generate from internal/pspdb/, so we go up two levels to reach the root.
const vendoredPath = "../../vendored/pspdb/PSP.titles.json"

// outputPath is relative to the working directory set by go generate,
// which is the source directory of the package containing the directive
// (i.e. internal/pspdb/).
const outputPath = "pspdb_generated.go"

func main() {
	fmt.Printf("Reading PSP title database from %s\n", vendoredPath)

	data, err := os.ReadFile(vendoredPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read vendored file: %v\n", err)
		fmt.Fprintf(os.Stderr, "hint: run the following to update the vendored file:\n")
		fmt.Fprintf(os.Stderr, "  curl -sL %s -o vendored/pspdb/PSP.titles.json\n", GameDBPSPURL)
		os.Exit(1)
	}

	var titles map[string]string
	if err := json.Unmarshal(data, &titles); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse JSON: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Loaded %d PSP titles\n", len(titles))

	ids := make([]string, 0, len(titles))
	for id := range titles {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen-psp-rom-list; DO NOT EDIT.\n\n")
	sb.WriteString("package pspdb\n\n")
	sb.WriteString("// Titles maps PSP Game IDs to their canonical game titles.\n")
	sb.WriteString("// Source: https://github.com/niemasd/GameDB-PSP\n")
	sb.WriteString("var Titles = map[string]string{\n")
	for _, id := range ids {
		cleanID := strings.NewReplacer("-", "", " ", "").Replace(id)
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", cleanID, titles[id]))
	}
	sb.WriteString("}\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d entries)\n", outputPath, len(titles))
}
