package utils

import (
	"regexp"

	gaba "github.com/UncleJunVIP/gabagool/v2/pkg/gabagool"
)

const (
	ExitCodeEditMappings gaba.ExitCode = 100
	ExitCodeClearSearch  gaba.ExitCode = 101
	ExitCodeNoResults    gaba.ExitCode = 404
)

const muOSRomsFolderUnion = "/mnt/union/ROMS"
const nextUIRomsFolder = "/mnt/SDCARD/Roms/"

var TagRegex = regexp.MustCompile(`\((.*?)\)`)
var OrderedFolderRegex = regexp.MustCompile(`\d+\)\s`)

// The following maps take a RomM Slug and return a list of folder names / system tags that can be used to map platforms

var muOSPlatforms = map[string][]string{
	"3do":                                {"3do"},
	"acpc":                               {"cpc", "gx4000"},
	"amiga":                              {"amiga"},
	"arcade":                             {"arcade", "mame", "cps1", "cps2", "cps3", "fba", "fbneo"},
	"arduboy":                            {},
	"atari-st":                           {},
	"atari2600":                          {"a2600", "atari"},
	"atari5200":                          {"a5200"},
	"atari7800":                          {"a7800"},
	"c128":                               {},
	"c64":                                {"c64"},
	"cave-story":                         {},
	"cbm-ii":                             {},
	"chailove":                           {},
	"chip-8":                             {},
	"colecovision":                       {},
	"cpet":                               {},
	"dc":                                 {"dc", "dreamcast"},
	"dos":                                {},
	"doom":                               {},
	"fairchild-channel-f":                {"channelf"},
	"fds":                                {"fds"},
	"g-and-w":                            {"gw"},
	"galaksija":                          {},
	"gamegear":                           {"gg"},
	"gb":                                 {"gb"},
	"gba":                                {"gba"},
	"gbc":                                {"gbc"},
	"genesis":                            {"genesis", "md", "nomad"},
	"intellivision":                      {"intv"},
	"j2me":                               {"j2me", "java"},
	"jaguar":                             {"jaguar"},
	"karaoke":                            {},
	"lowres":                             {"lowresnx"},
	"lua":                                {},
	"lynx":                               {"lynx"},
	"media-player":                       {"iptv"},
	"mega-duck-slash-cougar-boy":         {"megaduck"},
	"msx":                                {"msx", "msx2"},
	"n64":                                {"n64"},
	"naomi":                              {"naomi", "atomiswave"},
	"nds":                                {"ds", "nds"},
	"neo-geo-cd":                         {"neocd"},
	"neo-geo-pocket":                     {"ngp"},
	"neo-geo-pocket-color":               {"ngpc"},
	"neogeoaes":                          {"neogeo"},
	"neogeomvs":                          {"neogeo"},
	"nes":                                {"nes", "fc"},
	"famicom":                            {"fc", "nes"},
	"odyssey--1":                         {"odyssey2"},
	"onscripter":                         {},
	"openbor":                            {"openbor"},
	"pc-8000":                            {},
	"pc-fx":                              {},
	"pc-9800-series":                     {},
	"philips-cd-i":                       {"cdi"},
	"pico-8":                             {},
	"pokemon-mini":                       {"poke", "pokemini"},
	"ports":                              {},
	"psp":                                {"psp"},
	"psx":                                {"ps", "ps1", "psx"},
	"quake":                              {},
	"rpg-maker":                          {"easyrpg"},
	"saturn":                             {"saturn"},
	"scummvm":                            {"scummvm"},
	"sega-master-system":                 {"ms", "sms"},
	"sega-pico":                          {},
	"sega32":                             {"sega32x"},
	"segacd":                             {"segacd", "mdcd"},
	"sg1000":                             {"sg1000"},
	"sharp-x68000":                       {"x68000", "x68k"},
	"sinclair-zx81":                      {"zx81"},
	"snes":                               {"snes", "sfc"},
	"sfam":                               {"sfc", "snes", "sufami"},
	"supergrafx":                         {"supergrafx"},
	"tg16":                               {"pce", "tg16", "turbografx"},
	"ti-83":                              {},
	"tic-80":                             {"tic80"},
	"turbografx-cd":                      {"pcecd", "tgcd", "turbografxcd"},
	"uzebox":                             {},
	"vectrex":                            {"vectrex"},
	"vemulator":                          {},
	"vic-20":                             {},
	"virtualboy":                         {"vb"},
	"vircon-32":                          {},
	"wasm-4":                             {"wasm4"},
	"watara-slash-quickshot-supervision": {"supervision"},
	"wolfenstein-3d":                     {},
	"wonderswan":                         {"ws"},
	"wonderswan-color":                   {"wsc"},
	"x1":                                 {"x1"},
	"zxs":                                {"spectrum"},
}

var nextUIPlatforms = map[string][]string{
	"3do":                                {},
	"3ds":                                {"Nintendo 3DS (3DS)"},
	"acpc":                               {"Amstrad CPC (CPC)"},
	"amiga":                              {"Amiga (PUAE)"},
	"arcade":                             {"Arcade (FBN)"},
	"arduboy":                            {},
	"atari-st":                           {},
	"atari2600":                          {"Atari 2600 (A2600)"},
	"atari5200":                          {"Atari 5200 (A5200)"},
	"atari7800":                          {"Atari 7800 (A7800)"},
	"c128":                               {"Commodore 128 (C128)"},
	"c64":                                {"Commodore 64 (C64)"},
	"cave-story":                         {},
	"cbm-ii":                             {},
	"chailove":                           {},
	"chip-8":                             {},
	"colecovision":                       {"Colecovision (COLECO)"},
	"cpet":                               {"Commodore PET (PET)"},
	"dc":                                 {},
	"dos":                                {},
	"doom":                               {"Doom (PRBOOM)"},
	"fairchild-channel-f":                {},
	"fds":                                {"Famicom Disk System (FDS)"},
	"g-and-w":                            {},
	"galaksija":                          {},
	"gamegear":                           {"Sega Game Gear (GG)"},
	"gb":                                 {"Game Boy (GB)"},
	"gba":                                {"Game Boy Advance (GBA)"},
	"gbc":                                {"Game Boy Color (GBC)"},
	"genesis":                            {"Sega Genesis (MD)"},
	"intellivision":                      {},
	"j2me":                               {},
	"jaguar":                             {},
	"karaoke":                            {},
	"lowres":                             {},
	"lua":                                {},
	"lynx":                               {"Atari Lynx (LYNX)"},
	"media-player":                       {},
	"mega-duck-slash-cougar-boy":         {},
	"msx":                                {"Microsoft MSX (MSX)"},
	"n64":                                {"Nintendo 64 (N64)"},
	"naomi":                              {},
	"nds":                                {"Nintendo DS (NDS)"},
	"neo-geo-cd":                         {},
	"neo-geo-pocket":                     {"Neo Geo Pocket (NGP)"},
	"neo-geo-pocket-color":               {"Neo Geo Pocket Color (NGPC)"},
	"neogeoaes":                          {},
	"neogeomvs":                          {},
	"nes":                                {"Nintendo Entertainment System (FC)"},
	"famicom":                            {"Nintendo Entertainment System (FC)"},
	"odyssey--1":                         {},
	"onscripter":                         {},
	"openbor":                            {},
	"pc-8000":                            {},
	"pc-fx":                              {},
	"pc-9800-series":                     {},
	"philips-cd-i":                       {},
	"pico-8":                             {"Pico-8 (P8)"},
	"pokemon-mini":                       {"Pokémon mini (PKM)"},
	"ports":                              {},
	"psp":                                {"Sony PlayStation Portable (PSP)"},
	"psx":                                {"Sony PlayStation (PS)"},
	"ps2":                                {"Sony PlayStation 2 (PS2)"},
	"quake":                              {},
	"rpg-maker":                          {},
	"saturn":                             {},
	"scummvm":                            {},
	"sega-master-system":                 {"Sega Master System (SMS)"},
	"sega-pico":                          {},
	"sega32":                             {"Sega 32X (32X)"},
	"segacd":                             {"Sega CD (SEGACD)"},
	"sg1000":                             {"Sega SG-1000 (SG1000)"},
	"sharp-x68000":                       {},
	"sinclair-zx81":                      {},
	"snes":                               {"Super Nintendo Entertainment System (SFC)"},
	"sfam":                               {"Super Nintendo Entertainment System (SFC)"},
	"supergrafx":                         {},
	"tg16":                               {"TurboGrafx-16 (PCE)"},
	"ti-83":                              {},
	"tic-80":                             {},
	"turbografx-cd":                      {},
	"uzebox":                             {},
	"vectrex":                            {},
	"vemulator":                          {},
	"vic-20":                             {"Commodore VIC20 (VIC)"},
	"virtualboy":                         {"Virtual Boy (VB)"},
	"vircon-32":                          {},
	"wasm-4":                             {},
	"watara-slash-quickshot-supervision": {},
	"wolfenstein-3d":                     {},
	"wonderswan":                         {"WS"},
	"wonderswan-color":                   {"WSC"},
	"x1":                                 {},
	"zxs":                                {},
}
