package utils

const muOSRomsFolderMMC = "/mnt/mmc/ROMS/"
const muOSRomsFolderSD = "/mnt/sdcard/ROMS/"

const nextUIRomsFolder = "/mnt/SDCARD/Roms/"

// The following maps take a RomM Slug and return a list of folder names / system tags that can be used to map platforms
// TODO this will need to be reviewed
var muOSPlatforms = map[string][]string{
	"acpc":                               {"cpc", "gx4000"},
	"arcade":                             {"arcade", "mame", "cps1", "cps2", "cps3", "fba", "fbneo"},
	"arduboy":                            {},
	"atari2600":                          {"a2600", "atari"},
	"atari5200":                          {"a5200"},
	"atari7800":                          {"a7800"},
	"jaguar":                             {"jaguar"},
	"lynx":                               {"lynx"},
	"atari-st":                           {},
	"wonderswan":                         {"ws"},
	"wonderswan-color":                   {"wsc"},
	"cave-story":                         {},
	"chailove":                           {},
	"chip-8":                             {},
	"colecovision":                       {},
	"amiga":                              {"amiga"},
	"c128":                               {},
	"c64":                                {"c64"},
	"cbm-ii":                             {},
	"cpet":                               {},
	"vic-20":                             {},
	"dos":                                {},
	"doom":                               {},
	"ports":                              {},
	"fairchild-channel-f":                {"channelf"},
	"vectrex":                            {"vectrex"},
	"galaksija":                          {},
	"g-and-w":                            {"gw"},
	"j2me":                               {"j2me", "java"},
	"karaoke":                            {},
	"lowres":                             {"lowresnx"},
	"lua":                                {},
	"odyssey--1":                         {"odyssey2"},
	"intellivision":                      {"intv"},
	"media-player":                       {"iptv"},
	"mega-duck-slash-cougar-boy":         {"megaduck"},
	"msx":                                {"msx", "msx2"},
	"turbografx-cd":                      {"pcecd", "tgcd", "turbografxcd"},
	"tg16":                               {"pce", "tg16", "turbografx"},
	"supergrafx":                         {"supergrafx"},
	"pc-8000":                            {},
	"pc-fx":                              {},
	"pc-9800-series":                     {},
	"nds":                                {"ds", "nds"},
	"fds":                                {"fds"},
	"gba":                                {"gba"},
	"gbc":                                {"gbc"},
	"gb":                                 {"gb"},
	"n64":                                {"n64"},
	"nes":                                {"nes", "fc"},
	"famicom":                            {"fc", "nes"},
	"snes":                               {"snes", "sfc"},
	"sfam":                               {"sfc", "snes", "sufami"},
	"pokemon-mini":                       {"poke", "pokemini"},
	"virtualboy":                         {"vb"},
	"onscripter":                         {},
	"openbor":                            {"openbor"},
	"pico-8":                             {},
	"philips-cd-i":                       {"cdi"},
	"quake":                              {},
	"rpg-maker":                          {"easyrpg"},
	"neogeoaes":                          {"neogeo"},
	"neogeomvs":                          {"neogeo"},
	"neo-geo-cd":                         {"neocd"},
	"neo-geo-pocket":                     {"ngp"},
	"neo-geo-pocket-color":               {"ngpc"},
	"scummvm":                            {"scummvm"},
	"sega32":                             {"sega32x"},
	"naomi":                              {"naomi", "atomiswave"},
	"dc":                                 {"dc", "dreamcast"},
	"gamegear":                           {"gg"},
	"sega-master-system":                 {"ms", "sms"},
	"genesis":                            {"genesis", "md", "nomad"},
	"sega-pico":                          {},
	"segacd":                             {"segacd", "mdcd"},
	"sg1000":                             {"sg1000"},
	"saturn":                             {"saturn"},
	"x1":                                 {"x1"},
	"sharp-x68000":                       {"x68000", "x68k"},
	"sinclair-zx81":                      {"zx81"},
	"zxs":                                {"spectrum"},
	"psx":                                {"ps", "ps1", "psx"},
	"psp":                                {"psp"},
	"tic-80":                             {"tic80"},
	"ti-83":                              {},
	"3do":                                {"3do"},
	"uzebox":                             {},
	"vemulator":                          {},
	"vircon-32":                          {},
	"wasm-4":                             {"wasm4"},
	"watara-slash-quickshot-supervision": {"supervision"},
	"wolfenstein-3d":                     {},
}

var NextUIPlatforms = map[string][]string{
	"CPC":    {"acpc"},
	"PUAE":   {"amiga"},
	"FBN":    {"arcade"},
	"A2600":  {"atari2600"},
	"A5200":  {"atari5200"},
	"A7800":  {"atari7800"},
	"C128":   {"c128"},
	"C64":    {"c64"},
	"COLECO": {"colecovision"},
	"PET":    {"cpet"},
	"PRBOOM": {"doom"},
	"FDS":    {"fds"},
	"GG":     {"gamegear"},
	"GB":     {"gb"},
	"GBA":    {"gba"},
	"GBC":    {"gbc"},
	"MD":     {"genesis"},
	"LYNX":   {"lynx"},
	"MSX":    {"msx"},
	"N64":    {"n64"},
	"NGP":    {"neo-geo-pocket"},
	"NGPC":   {"neo-geo-pocket-color"},
	"FC":     {"nes"},
	"P8":     {"pico-8"},
	"PKM":    {"pokemon-mini"},
	"PS":     {"psx"},
	"SMS":    {"sega-master-system"},
	"32X":    {"sega32"},
	"SEGACD": {"segacd"},
	"SG1000": {"sg1000"},
	"SFC":    {"snes"},
	"PCE":    {"tg16"},
	"VIC":    {"vic-20"},
	"VB":     {"virtualboy"},
	"WSC":    {"wonderswan", "wonderswan-color"},
}
